# Generated by Django 4.2.28 on 2026-02-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='About',
        ),
    ]
